#define dtrans_	 dtrans
#define dasum_	 dasum
#define daxpy_	 daxpy
#define dcabs1_	 dcabs1
#define dcopy_	 dcopy
#define ddot_	 ddot
#define dgbmv_	 dgbmv
#define dgemm_	 dgemm
#define dgemv_	 dgemv
#define dger_	 dger
#define dnrm2_	 dnrm2
#define drot_	 drot
#define drotg_	 drotg
#define dsbmv_	 dsbmv
#define dscal_	 dscal
#define dspmv_	 dspmv
#define dspr_	 dspr
#define dspr2_	 dspr2
#define dswap_	 dswap
#define dsymm_	 dsymm
#define dsymv_	 dsymv
#define dsyr_	 dsyr
#define dsyr2_	 dsyr2
#define dsyr2k_	 dsyr2k
#define dsyrk_	 dsyrk
#define dtbmv_	 dtbmv
#define dtbsv_	 dtbsv
#define dtpmv_	 dtpmv
#define dtpsv_	 dtpsv
#define dtrmm_	 dtrmm
#define dtrmv_	 dtrmv
#define dtrsm_	 dtrsm
#define dtrsv_	 dtrsv
#define dzasum_	 dzasum
#define dznrm2_	 dznrm2
#define icamax_	 icamax
#define idamax_	 idamax
#define isamax_	 isamax
#define izamax_	 izamax
#define lsame_	 lsame
#define xerbla_	 xerbla
