function b=consistent(da)
% b=consistent(da)

%   G. Raetsch 1.6.98
%   Copyright (c) 1998  GMD Berlin - All rights reserved
%   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of GMD FIRST Berlin
%   The copyright notice above does not evidence any
%   actual or intended publication of this work.

b=(size(da.train_pat,2)==size(da.train_targ,2)) & ...
  (size(da.test_pat,2)==size(da.test_targ,2)) & ...
  (size(da.val_pat,2)==size(da.val_targ,2)) & ...
  ((size(da.val_pat,1)==size(da.train_pat,1)) | (size(da.val_pat,1)==0))& ...
  ((size(da.test_pat,1)==size(da.train_pat,1)) | (size(da.test_pat,1)==0)) & ...
  ((size(da.val_targ,1)==size(da.train_targ,1)) | (size(da.val_pat,1)==0)) & ...
  ((size(da.test_targ,1)==size(da.train_targ,1)) | (size(da.test_pat,1)==0)) ;